### ISSUE TITLE
Local development setup help

### ISSUE THREAD

**Issue by feardragon64** [TheBB/aligulac#299]
Hello! I was interested in trying to get aligulac running locally so I can hopefully work on optimizing some of the slower queries, etc. I was running into some issues while getting this running locally.

First I want to verify that this all runs on python3. The README said python 2.7 but I saw a lot of the files in the repo had a python3 header and when trying to run the server in 2.7 I hit a lot of encoding issues with characters, so I assume the readme is just out of date.

Second I am hitting an error when running the server in python 3. It seems to be some problem with the dependencies as far as I can tell. My `pip list` shows(ofc not all of it, just the relevant part):
```
Django               1.8.19
django-debug-toolbar 1.11
```

But when I try to start the django server I get this error:
```(venv) ravipareek~/aligulac/aligulac (master) $ python3 aligulac/manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1077418c8>
Traceback (most recent call last):
  File "/Users/ravipareek/aligulac/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/Users/ravipareek/aligulac/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 114, in inner_run
    self.validate(display_num_errors=True)
  File "/Users/ravipareek/aligulac/venv/lib/python3.7/site-packages/django/core/management/base.py", line 469, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "/Users/ravipareek/aligulac/venv/lib/python3.7/site-packages/django/core/management/base.py", line 482, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/ravipareek/aligulac/venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/ravipareek/aligulac/venv/lib/python3.7/site-packages/debug_toolbar/apps.py", line 20, in check_middleware
    from debug_toolbar.middleware import DebugToolbarMiddleware
  File "/Users/ravipareek/aligulac/venv/lib/python3.7/site-packages/debug_toolbar/middleware.py", line 12, in <module>
    from django.utils.deprecation import MiddlewareMixin
ImportError: cannot import name 'MiddlewareMixin' from 'django.utils.deprecation' (/Users/ravipareek/aligulac/venv/lib/python3.7/site-packages/django/utils/deprecation.py)
```

On a related note since this seems to be with the `django-debug-toolbar` dependency, I noticed that this error popped up when running `pip3 install -r requirements.txt`:
```
ERROR: django-debug-toolbar 1.11 has requirement Django>=1.11, but you'll have django 1.8.19 which is incompatible.
ERROR: django-sniplates 0.6.0 has requirement Django>=1.11, but you'll have django 1.8.19 which is incompatible.
```

Any help would be deeply appreciated! I noticed the `requirements.txt` file doesn't specify a version for `django-debug-toolbar` or `django-sniplates` so I was wondering if it was possible since the project development began, versions of these packages are no longer compatiable with the specificed Django version.

Thanks so much for the assistance. Hopefully I can get stuff up and running and start running some profiling on the website to find the right places to optimize, as well as update the README if it needs any updates.

**Comment by feardragon64** [comment]
Quick update: I managed to resolve this issue by updating `requirements.txt` to have the following versions specified, though I don't know if they are the most recent version that will work:
```
Django               1.8.19  
django-debug-toolbar 1.8     
django-sniplates     0.3.2
```

Might be good to specify the versions being used in production for the last two.

**Comment by TheBB** [comment]
Hey, great to hear some interest in this!

Here's `pip freeze` on the production venv:

    Django==1.8.3
    beautifulsoup4==4.4.0
    ccy==0.6.1
    django-debug-toolbar==1.3.2
    django-sniplates==0.3.1
    django-tastypie==0.12.2
    markdown2==2.3.0
    mwparserfromhell==0.6.dev0
    numpy==1.9.2
    psycopg2==2.6.1
    pyparsing==2.0.3
    python-dateutil==2.4.2
    python-mimeparse==0.1.4
    pytz==2015.4
    six==1.9.0
    sqlparse==0.1.16

It's probably not a bad idea to first start upgrading django though. The Python is indeed 3.4 and has been for a long time. If the readme says otherwise it's out of date.

**Comment by CAM-Gerlach** [comment]
@feardragon64 Python developer (core dev of the [Spyder IDE](https://www.spyder-ide.org/) and other scientific packages), web frontend novice (maintainer of [lektor-icon](https://spyder-ide.github.io/lektor-icon/) and a number of static CMS sites) and part-time Starcraft fan (and very occasional player) here.

These issues likely stem from ``pip`` not having a proper dependency solver like other package managers (e.g. ``conda``, or distro package managers like ``apt`` or ``rpm``). Because the ``django-debug-toolbar`` and ``django-sniplates`` plugins weren't manually pinned to versions compatible with this ancient version of Django that has been EoL, unsupported and obsolete for at least a year or two, ``pip`` naively pulled apparently the latest version, which is no longer compatible with unsupported versions of Django.

> It's probably not a bad idea to first start upgrading django though. 

This would be strongly recommended, since this version of Django hasn't been getting critical security updates for some time (not to mention bug fixes, performance optimizations and new features), and given this is a web-facing server, it would seem to be at decidedly non-trivial risk of exploitation (not just to steal data or infect visitors with malicious software, but also to e.g. launch DDoS attacks on other sites). 1.11 LTS would be an easier migration, but its in extended support and goes EoL in less than a year, whereas 2.2 LTS is the current version and has three full years of life left on it.

> The Python is indeed 3.4 and has been for a long time.

Similarly, Python 3.4 is now EoL after a 5 year lifespan, so it is time to upgrade, preferably straight to 3.7 since there aren't a ton of breaking changes, all current Django versions support it and it will be longer before you have to migrate again and less difficult when you do. All your dependencies in your ``requirements.txt`` declare official support and test against it, with the possible exception of ``django-tastypie`` which doesn't appear to yet run its full test suite against 3.7.

> git+https://github.com/earwig/mwparserfromhell.git

Is there a reason you don't just pull the PyPI package? They've been released promptly lately, the latest less than a week ago with only one commit since.

**Comment by 0BuRner** [comment]
@feardragon64 have you been able to setup a local environment based on @CAM-Gerlach recommandations ?

**Comment by feardragon64** [comment]
I did not try setting it up with @CAM-Gerlach's recommendations but I have it set up with the versions I listed above and the site seems to be working in full order for me locally. I haven't gotten around to load testing it to identify the problem queries yet but I believe anyone looking to get set up should be able to with those versions.

**Comment by CAM-Gerlach** [comment]
@feardragon64 Using obsolete, insecure, unsupported versions of multiple critical dependencies (including your foundational web framework and your language runtime) is a great way to open up the site to critical security vulnerabilities and troublesome bugs, miss out on major performance improvements in recent Python and Django versions (and it seems poor performance is the single biggest issue with the site right now), close the door on the numerous new features added in the course of 4-5 whole years of development, and make it much more annoying and unfriendly for new developers to get started working on the code.

What's more, upgrading to Python 3.7 and Django 1.11 should be close to a drop-in replacement, as your entire stack supports it (as discussed above) and the changes with compatibility implications are relatively minor. Django 2.x (i.e. 2,2 LTS) would likely be a bit more work, but would bring even more performance improvements and new features, be supported for many more years and likely help clean up and modernize the code base a bit in the process.

**Comment by feardragon64** [comment]
@CAM-Gerlach  Not to disagree but this isn't really my codebase, I haven't contributed a single line of code to the repo yet and I only got locally set up because I used the site a lot and the downtime was affecting my usage so I wanted to see if I could help debug it. If this is an important issue to you, it seems like a great place for you to get involved since it seems you've thought through the upgrade already.

**Comment by TheBB** [comment]
I'll try to put some time into Aligulac going forward, but I'm getting married in three weeks so it's going to be spotty at best for a while.

**Comment by CAM-Gerlach** [comment]
Oh wow, congratulations @TheBB ! Hope that all goes well!

In response to @feardragon64 , I would like to help at some point; I'm not really involved in the SC2 community other than as an occasional viewer and with spinning up a new research project for NASA, we've got a big launch coming up (Falcon Heavy STP-2) and also now moonlighting as a moderator of a 350 000 person subreddit (r/SpaceX), advice and minor assistance is all I can commit to right now given I've already been working hard enough on these projects that I was in the ER last week due to not having time to eat, sleep, drink, etc. in too many days. Thanks for understanding.

**Comment by mwiens91** [comment]
@TheBB Just want to confirm which version of Python you are using for this. The readme lists Python 2.x but `requirements.txt` seems to be using Python 3.x packages.

I'm interested in helping write up instructions for setting up a development server in the readme once I have time for it.

**Comment by TheBB** [comment]
Yeah, I'm using Python 3.6+. I don't know exactly which version of 3.x is the cutoff point, but 3.6 is ubiquitous enough for me.

**Comment by feardragon64** [comment]
Sorry I left this issue open. It's pretty resolved. Closing!
